### ISSUE TITLE
add a screenshot of the game to the README filte

### ISSUE THREAD

**Issue by JonasJore** [JonasJore/color-guessr#1]

**Comment by Dorcastunmise** [comment]
I'll suggest you insert the link to your app in the about section. So, people can screenshot when they view the app.

**Comment by JonasJore** [comment]
Thanks, the only reason there is no link in the description yet is because the app is not running anywhere right now. I will post a link as soon as it is running in an environment.

**Comment by Dorcastunmise** [comment]
Noted. Till then 🤝🏽

**Comment by JonasJore** [comment]
🤝🏽
